language: CSharp
sudo: required
mono:
  - latest
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - sudo apt-get install libunwind8 gettext libssl-dev libcurl3-dev zlib1g libicu-dev unzip
  - dnvm upgrade -r coreclr  
  - dnu restore
script:
  - dnx AspNet5-Awesome/test/AspNet5-Awesome.Tests/project.json test